Collect more stats
con/duct pull request #104
Opened 2024-06-19 20:22 UTC by asmacdo

- Report total memory usages (not just percentage)
- Collect averages (rss, vcz, pmem) for each report
- Collect averages for total run

```
$ duct --s-i 0.1 --r-i 0.1 -p ZZZZ_  --clobber ./test/data/test_script.py --duration 50 --memory-size 1000
duct is executing ./test/data/test_script.py --duration 50 --memory-size 1000...
Log files will be written to ZZZZ_
this is of test of STDERR
this is of test of STDOUT
Test completed. Consumed 1000 MB for 50 seconds with CPU load factor 10000.

Exit Code: 0
Command: ./test/data/test_script.py --duration 50 --memory-size 1000
Log files location: ZZZZ_
Wall Clock Time: 50.406 sec
Memory Peak Usage (RSS): 1035520 KiB
Memory Average Usage (RSS): 1031420.483 KiB
Virtual Memory Peak Usage (VSZ): 1258432 KiB
Virtual Memory Average Usage (VSZ): 1257865.920 KiB
Memory Peak Percentage: 3.1%
Memory Average Percentage: 3.088%
CPU Peak Usage: 118.0%
```

Needs tests

2024-06-20 20:19 UTC, asmacdo commented
The print statements have gotten to be quite messy, and this PR makes it worse, but I'll refactor that in https://github.com/con/duct/issues/64

2024-06-20 20:35 UTC, jwodder requested changes

2024-06-20 20:35 UTC, jwodder commented on src/duct/__main__.py
> +        self.num_samples = self.num_samples + 1
```suggestion
        self.num_samples += 1
```

2024-06-21 02:01 UTC, jwodder approved these changes

2024-06-21 02:33 UTC, merged