Fix typo in pmem calculation
con/duct pull request #151
Opened 2024-08-20 14:55 UTC by asmacdo

Fixes https://github.com/con/duct/issues/150

Also
 - use floats rather than ints for 0
 - add % to human readable summary

2024-08-20 16:31 UTC, yarikoptic requested changes
add a test . 
could mimic original invocation which observed that odd behavior: run `duct duct sleep 1` with some short periods for sampling/report

2024-08-20 18:10 UTC, yarikoptic commented
tests aren't happy , hadn't looked in detail yet.

2024-08-21 14:20 UTC, asmacdo commented
All the MacOS tests are failing because we cannot collect samples. The SANITY commit is not intended to be merged, its to show that there was plenty of time to collect a sample. This is related to https://github.com/con/duct/issues/82

2024-08-21 14:31 UTC, asmacdo commented
From one of the failing mac runs *Samples Collected: 0*, most likely because `ps -s` isnt an option.
```
Wall Clock Time: 1.139 sec
Memory Peak Usage (RSS): unknown bytes
Memory Average Usage (RSS): unknown bytes
Virtual Memory Peak Usage (VSZ): unknown bytes
Virtual Memory Average Usage (VSZ): unknown bytes
Memory Peak Percentage: unknown%
Memory Average Percentage: unknown%
CPU Peak Usage: unknown%
Average CPU Usage: unknown%
Samples Collected: 0
Reports Written: 0
```

2024-08-21 14:38 UTC, asmacdo commented
![image](https://github.com/user-attachments/assets/65f839e2-868b-4f30-bac9-f9f5bf64bfd2)

The tests didnt run, looks like a partial outage

2024-08-21 14:47 UTC, yarikoptic commented on .github/workflows/test.yaml
>            - macos-latest
```suggestion
          # - macos-latest
```

since unlikely to work there either

2024-08-21 14:57 UTC, merged